zipkin:
  enabled: true
  image:
    repository: openzipkin/zipkin
    tag: latest
  port: 9411
cloud-config:
  enabled: true
  image:
    repository: sjbs0212/cloud-config
    tag: latest
  port: 9296
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
service-discovery:
  enabled: true
  image:
    repository: sjbs0212/service-discovery
    tag: latest
  port: 8761
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
api-gateway:
  enabled: true
  image:
    repository: sjbs0212/api-gateway
    tag: latest
  port: 8080
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
proxy-client:
  enabled: true
  image:
    repository: sjbs0212/proxy-client
    tag: latest
  port: 8900
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
frontend:
  enabled: true
  image:
    repository: sjbs0212/frontend
    tag: latest
  port: 80
  env:
    API_HOST: "api-gateway"
    API_PORT: "8080"
    ENVIRONMENT: "development"
order-service:
  enabled: true
  image:
    repository: sjbs0212/order-service
    tag: latest
  port: 8300
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
payment-service:
  enabled: true
  image:
    repository: sjbs0212/payment-service
    tag: latest
  port: 8400
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
product-service:
  enabled: true
  image:
    repository: sjbs0212/product-service
    tag: latest
  port: 8500
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
shipping-service:
  enabled: true
  image:
    repository: sjbs0212/shipping-service
    tag: latest
  port: 8600
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
user-service:
  enabled: true
  image:
    repository: sjbs0212/user-service
    tag: latest
  port: 8700
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
favourite-service:
  enabled: true
  image:
    repository: sjbs0212/favourite-service
    tag: latest
  port: 8800
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"