{{- if .Values.frontendSecretRotation.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-secret-rotator-sa
  namespace: {{ .Release.Namespace }} # Se desplegará en el namespace del release (e.g., ecommerce-master)
  labels:
    app.kubernetes.io/name: frontend-secret-rotator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-secret-rotator-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: frontend-secret-rotator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["frontend-secret"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-secret-rotator-rb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: frontend-secret-rotator
subjects:
- kind: ServiceAccount
  name: frontend-secret-rotator-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: frontend-secret-rotator-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
