zipkin:
  image:
    repository: openzipkin/zipkin
    tag: latest
  enabled: true
  replicas: 1
cloud-config:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: cloud-config-stage-24
  enabled: true
  replicas: 1
service-discovery:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: service-discovery-stage-24
  enabled: true
  replicas: 1
api-gateway:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: api-gateway-stage-24
  enabled: true
  replicas: 1
proxy-client:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: proxy-client-stage-24
  enabled: true
  replicas: 1
frontend:
  image:
    repository: sjbs0212/ecommerce-frontend
    tag: latest
  enabled: true
  replicas: 1
order-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: order-service-stage-24
  enabled: true
  replicas: 1
payment-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: payment-service-stage-24
  enabled: true
  replicas: 1
product-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: product-service-stage-24
  enabled: true
  replicas: 1
shipping-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: shipping-service-stage-24
  enabled: true
  replicas: 1
user-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: user-service-stage-24
  enabled: true
  replicas: 1
favourite-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: favourite-service-stage-24
  enabled: true
  replicas: 1
ingress:
  enabled: false
