zipkin:
  image:
    repository: openzipkin/zipkin
    tag: latest
  enabled: true
  replicas: 1
cloud-config:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: cloud-config-20
  enabled: true
  replicas: 1
service-discovery:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: service-discovery-20
  enabled: true
  replicas: 1
api-gateway:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: api-gateway-20
  enabled: true
  replicas: 1
proxy-client:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: proxy-client-20
  enabled: true
  replicas: 1
frontend:
  image:
    repository: sjbs0212/ecommerce-frontend
    tag: latest
  enabled: true
  replicas: 1
order-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: order-service-20
  enabled: true
  replicas: 1
payment-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: payment-service-20
  enabled: true
  replicas: 1
product-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: product-service-20
  enabled: true
  replicas: 1
shipping-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: shipping-service-20
  enabled: true
  replicas: 1
user-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: user-service-20
  enabled: true
  replicas: 1
favourite-service:
  image:
    repository: 468720136030.dkr.ecr.us-east-1.amazonaws.com/proyectofinallsjecr
    tag: favourite-service-20
  enabled: true
  replicas: 1
ingress:
  enabled: true
  class: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
domains:
  frontend:
    host: www.lsj-app.xyz
    tlsSecret: frontend-tls
  api:
    host: api.lsj-app.xyz
    tlsSecret: api-gateway-tls
