zipkin:
  image:
    repository: openzipkin/zipkin
    tag: latest
  enabled: true
  replicas: 1
cloud-config:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/cloud-config-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
service-discovery:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/service-discovery-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
api-gateway:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/api-gateway-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
proxy-client:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/proxy-client-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
frontend:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/frontend-prod
    tag: v1.4.0
  enabled: true
  replicas: 1
order-service:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/order-service-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
payment-service:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/payment-service-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
product-service:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/product-service-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
shipping-service:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/shipping-service-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
user-service:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/user-service-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
favourite-service:
  image:
    repository: 211125706306.dkr.ecr.us-east-1.amazonaws.com/favourite-service-prod
    tag: v1.3.0
  enabled: true
  replicas: 1
ingress:
  enabled: true
  class: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
domains:
  frontend:
    host: www.lsj-app.xyz
    tlsSecret: frontend-tls
  api:
    host: api.lsj-app.xyz
    tlsSecret: api-gateway-tls
certManager:
  email: luiisapino.28@gmail.com
  enabled: true
