zipkin:
  image:
    repository: openzipkin/zipkin
    tag: latest
  enabled: true
  replicas: 1
cloud-config:
  image:
    repository: /proyectofinallsjecr
    tag: cloud-config-11
  enabled: true
  replicas: 1
service-discovery:
  image:
    repository: /proyectofinallsjecr
    tag: service-discovery-11
  enabled: true
  replicas: 1
api-gateway:
  image:
    repository: /proyectofinallsjecr
    tag: api-gateway-11
  enabled: true
  replicas: 1
proxy-client:
  image:
    repository: /proyectofinallsjecr
    tag: proxy-client-11
  enabled: true
  replicas: 1
frontend:
  image:
    repository: sjbs0212/ecommerce-frontend
    tag: latest
  enabled: true
  replicas: 1
order-service:
  image:
    repository: /proyectofinallsjecr
    tag: order-service-11
  enabled: true
  replicas: 1
payment-service:
  image:
    repository: /proyectofinallsjecr
    tag: payment-service-11
  enabled: true
  replicas: 1
product-service:
  image:
    repository: /proyectofinallsjecr
    tag: product-service-11
  enabled: true
  replicas: 1
shipping-service:
  image:
    repository: /proyectofinallsjecr
    tag: shipping-service-11
  enabled: true
  replicas: 1
user-service:
  image:
    repository: /proyectofinallsjecr
    tag: user-service-11
  enabled: true
  replicas: 1
favourite-service:
  image:
    repository: /proyectofinallsjecr
    tag: favourite-service-11
  enabled: true
  replicas: 1
ingress:
  enabled: true
  class: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
domains:
  frontend:
    host: www.lsj-app.xyz
    tlsSecret: frontend-tls
  api:
    host: api.lsj-app.xyz
    tlsSecret: api-gateway-tls