zipkin:
  enabled: true
  image:
    repository: openzipkin/zipkin
    tag: latest
  port: 9411
cloud-config:
  enabled: true
  image:
    repository: sjbs0212/cloud-config
    tag: latest
  port: 9296
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    EUREKA_INSTANCE_HOSTNAME: "cloud-config"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
service-discovery:
  enabled: true
  image:
    repository: sjbs0212/service-discovery
    tag: latest
  port: 8761
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
api-gateway:
  enabled: true
  image:
    repository: sjbs0212/api-gateway
    tag: latest
  port: 8080
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "api-gateway"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
proxy-client:
  enabled: true
  image:
    repository: sjbs0212/proxy-client
    tag: latest
  port: 8900
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "proxy-client"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
frontend:
  enabled: true
  image:
    repository: sjbs0212/ecommerce-frontend
    tag: latest
  port: 80
  env:
    API_HOST: "api-gateway"
    API_PORT: "8080"
    ENVIRONMENT: "development"
    SECRET_TEXT: "default-secret-if-not-overridden"

frontendSecretRotation:
  enabled: true
  # Schedule para el CronJob. Ver https://crontab.guru/
  # Ejemplo: cada 5 minutos '*/5 * * * *'
  # Ejemplo: cada hora '0 * * * *'
  schedule: "*/1 * * * *" 
  baseSecretValue: "default-secret-if-not-overridden" # El prefijo que se mantendrá

order-service:
  enabled: true
  image:
    repository: sjbs0212/order-service
    tag: latest
  port: 8300
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "order-service"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
payment-service:
  enabled: true
  image:
    repository: sjbs0212/payment-service
    tag: latest
  port: 8400
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "payment-service"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
product-service:
  enabled: true
  image:
    repository: sjbs0212/product-service
    tag: latest
  port: 8500
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "product-service"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
shipping-service:
  enabled: true
  image:
    repository: sjbs0212/shipping-service
    tag: latest
  port: 8600
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "shipping-service"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
user-service:
  enabled: true
  image:
    repository: sjbs0212/user-service
    tag: latest
  port: 8700
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "user-service"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
favourite-service:
  enabled: true
  image:
    repository: sjbs0212/favourite-service
    tag: latest
  port: 8800
  env:
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    EUREKA_CLIENT_REGION: "default"
    EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
    EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
    SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296/"
    EUREKA_INSTANCE_HOSTNAME: "favourite-service"
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"

certManager:
  email: luiisapino.28@gmail.com
  enabled: false
