{{- if index .Values "cloud-config" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: {{ index .Values "cloud-config" "replicas" }}
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: {{ index .Values "cloud-config" "image" "repository" }}:{{ index .Values "cloud-config" "image" "tag" }}
        ports:
        - containerPort: {{ index .Values "cloud-config" "port" }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_PROFILES_ACTIVE

        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_ZIPKIN_BASE_URL

        - name: EUREKA_CLIENT_REGION
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_REGION

        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT

        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_SERVICEURL_MYZONE

        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_INSTANCE_PREFER_IP_ADDRESS

        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: cloud-config.EUREKA_INSTANCE_HOSTNAME

        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"

        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      initContainers:
      - name: wait-for-dependencies
        image: busybox
        command: ['sh', '-c', 'until nc -z zipkin 9411 && nc -z service-discovery 8761; do echo waiting for dependencies; sleep 2; done;']
{{- end }}