{{- if index .Values "order-service" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: {{ index .Values "order-service" "replicas" }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: {{ index .Values "order-service" "image" "repository" }}:{{ index .Values "order-service" "image" "tag" }}
        ports:
        - containerPort: {{ index .Values "order-service" "port" }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_ZIPKIN_BASE_URL
        - name: EUREKA_CLIENT_REGION
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_REGION
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_SERVICEURL_MYZONE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: order-service.EUREKA_INSTANCE_HOSTNAME
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_INSTANCE_PREFER_IP_ADDRESS

        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0"

        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      initContainers:
      - name: wait-for-dependencies
        image: busybox
        command: ['sh', '-c', 'until nc -z zipkin 9411 && nc -z cloud-config 9296 && nc -z service-discovery 8761; do echo waiting for dependencies; sleep 2; done;']
{{- end }}