{{- if index .Values "product-service" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: {{ index .Values "product-service" "port" }}
    targetPort: {{ index .Values "product-service" "port" }}
  type: ClusterIP
{{- end }}