{{- if index .Values "service-discovery" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: {{ index .Values "service-discovery" "replicas" }}
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: {{ index .Values "service-discovery" "image" "repository" }}:{{ index .Values "service-discovery" "image" "tag" }}
        ports:
        - containerPort: {{ index .Values "service-discovery" "port" }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_ZIPKIN_BASE_URL
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: SPRING_CONFIG_IMPORT
      initContainers:
      - name: wait-for-dependencies
        image: busybox
        command: ['sh', '-c', 'until nc -z zipkin 9411; do echo waiting for dependencies; sleep 2; done;']
{{- end }}