{{- if .Values.zipkin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: {{ .Values.zipkin.replicas }}
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: {{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}
        ports:
        - containerPort: {{ .Values.zipkin.port }}
{{- end }}
