apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-master
  namespace: argocd
  labels:
    environment: master
    app: ecommerce
spec:
  project: ecommerce-project
  source:
    repoURL: https://github.com/microservices-project-k8s-jenkins/ecommerce-charts.git
    targetRevision: HEAD
    path: charts/ecommerce
    helm:
      valueFiles:
        - values-master.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    managedNamespaceMetadata:
      labels:
        linkerd.io/inject: enabled
        environment: master
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
  - group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
    jsonPointers:
    - /spec/acme/solvers/0/http01/ingress/pathType
  - group: ""
    kind: Secret
    name: frontend-secret
    namespace: ecommerce-master
    jsonPointers:
    - /data/SECRET_TEXT