apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana
  namespace: argocd
  labels:
    environment: monitoring
    app: grafana
spec:
  project: ecommerce-project
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.7 # o versión estable compatible
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/microservices-project-k8s-jenkins/ecommerce-charts/HEAD/charts/monitoring/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
