apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prometheus
  namespace: argocd
  labels:
    environment: monitoring
    app: prometheus
spec:
  project: ecommerce-project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 57.0.3 # o la versión que desees
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/microservices-project-k8s-jenkins/ecommerce-charts/HEAD/charts/monitoring/prometheus/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
