{{- if index .Values "cloud-config" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: {{ index .Values "cloud-config" "replicas" }}
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: {{ index .Values "cloud-config" "image" "repository" }}:{{ index .Values "cloud-config" "image" "tag" }}
        ports:
        - containerPort: {{ index .Values "cloud-config" "port" }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ index .Values "cloud-config" "env" "SPRING_PROFILES_ACTIVE" }}
        - name: SPRING_ZIPKIN_BASE_URL
          value: {{ index .Values "cloud-config" "env" "SPRING_ZIPKIN_BASE_URL" }}
        - name: EUREKA_CLIENT_REGION
          value: {{ index .Values "cloud-config" "env" "EUREKA_CLIENT_REGION" }}
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: {{ index .Values "cloud-config" "env" "EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT" }}
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: {{ index .Values "cloud-config" "env" "EUREKA_CLIENT_SERVICEURL_MYZONE" }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: {{ index .Values "cloud-config" "env" "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE" }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ index .Values "cloud-config" "port" }}
          initialDelaySeconds: 30
          periodSeconds: 10
      initContainers:
      - name: wait-for-zipkin
        image: busybox
        command: ['sh', '-c', 'until nc -z zipkin 9411; do echo waiting for zipkin; sleep 2; done;']
{{- end }}