{{ if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: API_HOST
              value: "{{ .Values.frontend.env.API_HOST }}"
            - name: API_PORT
              value: "{{ .Values.frontend.env.API_PORT }}"
            - name: ENVIRONMENT
              value: "{{ .Values.frontend.env.ENVIRONMENT }}"
      initContainers:
      - name: wait-for-api-gateway
        image: busybox
        command: ['sh', '-c', 'until nc -z api-gateway 8080; do echo waiting for api-gateway; sleep 2; done;']
{{ end }}