{{- if .Values.payment-service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: {{ .Values.payment-service.port }}
    targetPort: {{ .Values.payment-service.port }}
  type: ClusterIP
{{- end }}