{{- if index .Values "payment-service" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: {{ index .Values "payment-service" "port" }}
    targetPort: {{ index .Values "payment-service" "port" }}
  type: ClusterIP
{{- end }}