{{- if .Values.proxy-client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
spec:
  selector:
    app: proxy-client
  ports:
  - port: {{ .Values.proxy-client.port }}
    targetPort: {{ .Values.proxy-client.port }}
  type: ClusterIP
{{- end }}