{{- if index .Values "user-service" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: {{ index .Values "user-service" "port" }}
      targetPort: {{ index .Values "user-service" "port" }}
  type: ClusterIP
{{- end }}