apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-elastic-stack-internal-communication
  namespace: elastic-stack 
spec:
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  ingress:
    - from:
        - podSelector:
            matchLabels:
              common.k8s.elastic.co/type: elasticsearch
      ports:
        - protocol: TCP
          port: 9200
        - protocol: TCP
          port: 9300
    - from:
        - podSelector:
            matchLabels:
              common.k8s.elastic.co/type: kibana
      ports:
        - protocol: TCP
          port: 9200
    - from:
        - podSelector:
            matchLabels:
              common.k8s.elastic.co/type: logstash
      ports:
        - protocol: TCP
          port: 9200
  policyTypes:
    - Ingress