apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-linkerd-internal
  namespace: linkerd
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector: {}
    - from:
      - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 9995
  egress:
    - {}