apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-shipping-and-product
spec:
  podSelector:
    matchLabels:
      app: shipping-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: product-service
      ports:
        - protocol: TCP
          port: 8600
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: product-service
      ports:
        - protocol: TCP
          port: 8500
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-product-and-shipping
spec:
  podSelector:
    matchLabels:
      app: product-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: shipping-service
      ports:
        - protocol: TCP
          port: 8500
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: shipping-service
      ports:
        - protocol: TCP
          port: 8600