apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-elasticsearch
  namespace: elastic-stack
spec:
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            common.k8s.elastic.co/type: elasticsearch
      ports:
        - protocol: TCP
          port: 9300
        - protocol: TCP
          port: 9200
    - from:
      - podSelector:
          matchLabels:
            common.k8s.elastic.co/type: kibana
      ports:
        - protocol: TCP
          port: 9200
    - from:
      - podSelector:
          matchLabels:
            common.k8s.elastic.co/type: logstash
      ports:
        - protocol: TCP
          port: 9200
    - from:
      - podSelector:
          matchLabels:
            common.k8s.elastic.co/type: beat
      ports:
        - protocol: TCP
          port: 9200
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-kibana
  namespace: elastic-stack
spec:
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: kibana
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            common.k8s.elastic.co/type: elasticsearch
      ports:
        - protocol: TCP
          port: 9200
    - to:
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-beats-logstash
  namespace: elastic-stack
spec:
  podSelector:
    matchExpressions:
      - key: common.k8s.elastic.co/type
        operator: In
        values: ["logstash", "beat"]
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            common.k8s.elastic.co/type: elasticsearch
      ports:
        - protocol: TCP
          port: 9200
    - to:
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53