apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-shipping-from-proxy
spec:
  podSelector:
    matchLabels:
      app: shipping-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy-client
      ports:
        - protocol: TCP
          port: 8600
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-payment-from-proxy
spec:
  podSelector:
    matchLabels:
      app: payment-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy-client
      ports:
        - protocol: TCP
          port: 8400
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-order-from-proxy
spec:
  podSelector:
    matchLabels:
      app: order-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy-client
      ports:
        - protocol: TCP
          port: 8300
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-user-from-proxy
spec:
  podSelector:
    matchLabels:
      app: user-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy-client
      ports:
        - protocol: TCP
          port: 8700
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-favourite-from-proxy
spec:
  podSelector:
    matchLabels:
      app: favourite-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy-client
      ports:
        - protocol: TCP
          port: 8800
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-product-from-proxy
spec:
  podSelector:
    matchLabels:
      app: product-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy-client
      ports:
        - protocol: TCP
          port: 8500