apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-user-and-favourite
spec:
  podSelector:
    matchLabels:
      app: user-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: favourite-service
      ports:
        - protocol: TCP
          port: 8700
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-favourite-and-user
spec:
  podSelector:
    matchLabels:
      app: favourite-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: user-service
      ports:
        - protocol: TCP
          port: 8800