apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-service-ingress
spec:
  podSelector:
    matchLabels:
      app: service-discovery
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: shipping-service
        - podSelector:
            matchLabels:
              app: product-service
        - podSelector:
            matchLabels:
              app: order-service
        - podSelector:
            matchLabels:
              app: payment-service
        - podSelector:
            matchLabels:
              app: user-service
        - podSelector:
            matchLabels:
              app: favourite-service
        - podSelector:
            matchLabels:
              app: cloud-config
        - podSelector:
            matchLabels:
              app: zipkin
        - podSelector:
            matchLabels:
              app: proxy-client
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8761
